name: CI and Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
    - name: Install Dependencies
      run: npm ci
    - name: Run Unit Tests
      run: npm run test
    - name: Run E2E Tests
      run: |
        npm run start &
        SERVER_PID=$!
        sleep 5  # Дополнительная задержка
        npx wait-on http://localhost:8080 --timeout 60000
        curl -v http://localhost:8080  # Проверка доступности
        npm run test:e2e
        kill $SERVER_PID 2>/dev/null || true
    - name: Build
      run: npm run build
    - name: Deploy to GitHub Pages
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist