name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Установка Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Установка зависимостей
      run: npm ci

    - name: Сборка проекта
      run: npm run build

    - name: Запуск юнит-тестов
      run: npm test

    - name: Запуск E2E тестов
      run: npm run test:e2e